-- ※ 연습문제
-- DROP TABLE 지워야할 부모테이블 CASCADE CONSTRAINTS;
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
DROP SEQUENCE MEMBER_SQ;
CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(4) PRIMARY KEY,
    LEVELNAME VARCHAR2(50) NOT NULL
    );
ALTER TABLE MEMBER_LEVEL MODIFY LEVELNAME VARCHAR2(50) NOT NULL;
CREATE TABLE MEMBER(
    mNO NUMBER(4) PRIMARY KEY,
    mNAME VARCHAR2(50),
    mPW VARCHAR2(50),
    mMAIL VARCHAR2(200) UNIQUE,
    mPOINT NUMBER(10) CHECK (mPOINT >=0),
    mRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(4),
    FOREIGN KEY (LEVELNO) REFERENCES MEMBER_LEVEL(LEVELNO)
    );
ALTER TABLE MEMBER MODIFY MNAME VARCHAR2(50) NULL;
ALTER TABLE MEMBER MODIFY MPW VARCHAR2(50) NULL;
CREATE SEQUENCE MEMBER_SQ
    MAXVALUE 9999
    NOCACHE NOCYCLE;
-- INSERT INTO MEMBER_LEVEL ~
    INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (-1, 'black');
    INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (0, '일반');
    INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (MEMBER_SQ.NEXTVAL, '실버');
    INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (MEMBER_SQ.NEXTVAL, '골드');
    SELECT * FROM MEMBER_LEVEL;
-- INSERT INTO MEMBER ~
    INSERT INTO MEMBER (mNO, mNAME, mPW, mMAIL, mPOINT, LEVELNO) 
        VALUES (MEMBER_SQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, 0);
    INSERT INTO MEMBER (mNO, mNAME, mPW, mMAIL, mPOINT, LEVELNO) 
        VALUES (MEMBER_SQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 1000, 1);
    SELECT * FROM MEMBER;
-- 연습문제와 같이 출력되도록 SELECT (EQUI JOIN)
    SELECT M.MNO, M.MNAME, TO_CHAR(M.MRDATE, 'YYYY-MM-DD') MRDATE, M.MMAIL, M.MPOINT POINT, Z.LEVELNAME || '고객' levelname
        FROM MEMBER_LEVEL Z,
             MEMBER M
        WHERE M.LEVELNO = Z.LEVELNO;