-- [V] Sequence : 순차번호 생성기. 대부분 인위적인 PK 사용용도
    -- 시퀀스 만들기
    DROP SEQUENCE FRIEND_SEQ;
    CREATE SEQUENCE FRIEND_SEQ
        START WITH 1        -- 1부터 시작(기본값: 생략가능)
        INCREMENT BY 1      -- 1씩 증가(기본값)
        MAXVALUE 9999       -- 최대값
        MINVALUE 1          -- 최소값
        NOCYCLE             -- MAXVALUE에서 끝남 / CYCLE : 순차번호 9999 -> 1로 돌아가서 시작
        NOCACHE;            -- / CACHE n
    
    -- NEXTVAL 전체 출력
    SELECT FRIEND_SEQ.NEXTVAL FROM EMP;
    -- NEXTVAL 한줄만 출력 : 다음 순차번호 값
    SELECT FRIEND_SEQ.NEXTVAL FROM DUAL;
    -- 현재 NEXTVAL 시퀀스 값
    SELECT FRIEND_SEQ.CURRVAL FROM DUAL;
    
    -- 테이블 생성
    DROP TABLE FRIEND;
    CREATE TABLE FRIEND (
        NO NUMBER(5) PRIMARY KEY,
        NAME VARCHAR2(50) NOT NULL,
        TEL VARCHAR2(20) UNIQUE,
        ADDRESS VARCHAR2(250),
        LAST_MODIFI DATE DEFAULT SYSDATE
        );
        
    -- SEQUENCE 간단 생성
    DROP SEQUENCE FRIEND_SEQ;
    CREATE SEQUENCE FRIEND_SEQ
        MAXVALUE 99999
        NOCACHE NOCYCLE;
    SELECT * FROM FRIEND;
    
    -- INSERT INTO
    INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
        VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', '010-9999-9999', '서울');
    INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
        VALUES (FRIEND_SEQ.NEXTVAL, '유길동', NULL, '서울');
    SELECT * FROM FRIEND;
    DELETE FROM FRIEND WHERE TEL IS NULL;
    
-- ※ 연습문제
-- DROP TABLE 지워야할 부모테이블 CASCADE CONSTRAINTS;
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
DROP SEQUENCE MEMBER_SQ;
CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(4) PRIMARY KEY,
    LEVELNAME VARCHAR2(50) NOT NULL
    );
ALTER TABLE MEMBER_LEVEL MODIFY LEVELNAME VARCHAR2(50) NOT NULL;
CREATE TABLE MEMBER(
    mNO NUMBER(4) PRIMARY KEY,
    mNAME VARCHAR2(50),
    mPW VARCHAR2(50),
    mMAIL VARCHAR2(200) UNIQUE,
    mPOINT NUMBER(10) CHECK (mPOINT >=0),
    mRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(4),
    FOREIGN KEY (LEVELNO) REFERENCES MEMBER_LEVEL(LEVELNO)
    );
ALTER TABLE MEMBER MODIFY MNAME VARCHAR2(50) NULL;
ALTER TABLE MEMBER MODIFY MPW VARCHAR2(50) NULL;
CREATE SEQUENCE MEMBER_SQ
    MAXVALUE 9999
    NOCACHE NOCYCLE;
-- INSERT INTO MEMBER_LEVEL ~
    INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (-1, 'black');
    INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (0, '일반');
    INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (MEMBER_SQ.NEXTVAL, '실버');
    INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (MEMBER_SQ.NEXTVAL, '골드');
    SELECT * FROM MEMBER_LEVEL;
-- INSERT INTO MEMBER ~
    INSERT INTO MEMBER (mNO, mNAME, mPW, mMAIL, mPOINT, LEVELNO) 
        VALUES (MEMBER_SQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, 0);
    INSERT INTO MEMBER (mNO, mNAME, mPW, mMAIL, mPOINT, LEVELNO) 
        VALUES (MEMBER_SQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 1000, 1);
    SELECT * FROM MEMBER;
-- 연습문제와 같이 출력되도록 SELECT (EQUI JOIN)
    SELECT M.MNO, 
           M.MNAME, 
           TO_CHAR(M.MRDATE, 'YYYY-MM-DD') MRDATE, 
           M.MMAIL, 
           M.MPOINT POINT, 
           Z.LEVELNAME || '고객' levelname
        FROM MEMBER_LEVEL Z,
             MEMBER M
        WHERE M.LEVELNO = Z.LEVELNO;